pub var chars: [2048]packed struct {
    pos: u16 = 0,
    width: u16 = 3,
} = undefined;
pub fn init() void {
    for (chars, 0..) |_, i| chars[i] = .{ .pos = 0, .width = 3 };
    chars['!'] = .{ .pos = 3, .width = 1 };
    chars['"'] = .{ .pos = 4 };
    chars['#'] = .{ .pos = 7, .width = 5 };
    chars['$'] = .{ .pos = 12 };
    chars['\''] = .{ .pos = 15, .width = 1 };
    chars['('] = .{ .pos = 16, .width = 1 };
    chars[')'] = .{ .pos = 18, .width = 1 };
    chars['*'] = .{ .pos = 20 };
    chars['+'] = .{ .pos = 23 };
    chars[','] = .{ .pos = 26, .width = 1 };
    chars['-'] = .{ .pos = 27, .width = 2 };
    chars['.'] = .{ .pos = 29, .width = 1 };
    chars['/'] = .{ .pos = 30 };
    chars['0'] = .{ .pos = 33 };
    chars['1'] = .{ .pos = 36, .width = 2 };
    chars['2'] = .{ .pos = 38 };
    chars['3'] = .{ .pos = 41 };
    chars['4'] = .{ .pos = 44 };
    chars['5'] = .{ .pos = 47 };
    chars['6'] = .{ .pos = 50 };
    chars['7'] = .{ .pos = 53 };
    chars['8'] = .{ .pos = 56 };
    chars['9'] = .{ .pos = 59 };
    chars[':'] = .{ .pos = 62, .width = 1 };
    chars[';'] = .{ .pos = 63, .width = 1 };
    chars['<'] = .{ .pos = 64 };
    chars['='] = .{ .pos = 67 };
    chars['>'] = .{ .pos = 70 };
    chars['?'] = .{ .pos = 73 };
    chars['@'] = .{ .pos = 76, .width = 5 };
    chars['a'] = .{ .pos = 81 };
    chars['b'] = .{ .pos = 84 };
    chars['c'] = .{ .pos = 87 };
    chars['d'] = .{ .pos = 90 };
    chars['e'] = .{ .pos = 93 };
    chars['f'] = .{ .pos = 96 };
    chars['g'] = .{ .pos = 99 };
    chars['h'] = .{ .pos = 102 };
    chars['i'] = .{ .pos = 105, .width = 1 };
    chars['j'] = .{ .pos = 106 };
    chars['k'] = .{ .pos = 109 };
    chars['l'] = .{ .pos = 112 };
    chars['m'] = .{ .pos = 115, .width = 5 };
    chars['n'] = .{ .pos = 120, .width = 4 };
    chars['o'] = .{ .pos = 124 };
    chars['p'] = .{ .pos = 127 };
    chars['q'] = .{ .pos = 130 };
    chars['r'] = .{ .pos = 133 };
    chars['s'] = .{ .pos = 136 };
    chars['t'] = .{ .pos = 139 };
    chars['u'] = .{ .pos = 142 };
    chars['v'] = .{ .pos = 145 };
    chars['w'] = .{ .pos = 148 };
    chars['x'] = .{ .pos = 153 };
    chars['y'] = .{ .pos = 156 };
    chars['z'] = .{ .pos = 159 };
    chars['['] = .{ .pos = 162, .width = 2 };
    chars['\\'] = .{ .pos = 164, .width = 3 };
    chars[']'] = .{ .pos = 167, .width = 2 };
    chars['^'] = .{ .pos = 169 };
    chars['_'] = .{ .pos = 172 };
    chars['а'] = .{ .pos = 175 };
    chars['б'] = .{ .pos = 178 };
    chars['в'] = .{ .pos = 181 };
    chars['г'] = .{ .pos = 184 };
    chars['д'] = .{ .pos = 187, .width = 5 };
    chars['е'] = .{ .pos = 192 };
    chars['ё'] = .{ .pos = 195 };
    chars['ж'] = .{ .pos = 198, .width = 5 };
    chars['з'] = .{ .pos = 203 };
    chars['и'] = .{ .pos = 206, .width = 4 };
    chars['й'] = .{ .pos = 210, .width = 4 };
    chars['к'] = .{ .pos = 214 };
    chars['л'] = .{ .pos = 217 };
    chars['м'] = .{ .pos = 220, .width = 5 };
    chars['н'] = .{ .pos = 225 };
    chars['о'] = .{ .pos = 228 };
    chars['п'] = .{ .pos = 231 };
    chars['р'] = .{ .pos = 234 };
    chars['с'] = .{ .pos = 237 };
    chars['т'] = .{ .pos = 240 };
    chars['у'] = .{ .pos = 243 };
    chars['ф'] = .{ .pos = 246, .width = 5 };
    chars['х'] = .{ .pos = 251 };
    chars['ц'] = .{ .pos = 254 };
    chars['ч'] = .{ .pos = 257 };
    chars['ш'] = .{ .pos = 260, .width = 5 };
    chars['щ'] = .{ .pos = 265, .width = 5 };
    chars['ъ'] = .{ .pos = 270, .width = 4 };
    chars['ы'] = .{ .pos = 274, .width = 5 };
    chars['ь'] = .{ .pos = 279 };
    chars['э'] = .{ .pos = 282, .width = 4 };
    chars['ю'] = .{ .pos = 286, .width = 5 };
    chars['я'] = .{ .pos = 291 };
}
